print("hello")
print("yakarsa dünyayı garipler yakar")
print("hello")
print("yakarsa dünyayı garipler yakar")
print("hello")
print("yakarsa dünyayı garipler yakar")
print("hello")
print("yakarsa dünyayı garipler yakar")
